apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-django-app-deployment
  namespace: production
  labels:
    app: simple-django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-django-app
  template:
    metadata:
      labels:
        app: simple-django-app
    spec:
      containers:
      - name: simple-django-app
        image: tapashranjannandi/simple-django-app-1:v1
        ports:
        - containerPort: 8000
        env: 
          - name: ALLOWED_HOSTS
            value: "*"

