apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-django-app-deployment
  labels:
    app: simple-django-app-green
    color: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-django-app-green
      color: green
  template:
    metadata:
      labels:
        app: simple-django-app-green
        color: green
    spec:
      containers:
      - name: simple-django-app-green
        image: tapashranjannandi/simple-django-app-1:green
        ports:
        - containerPort: 8000
        env: 
          - name: ALLOWED_HOSTS
            value: "*"

