apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-django-app-deployment
  labels:
    app: simple-django-app
    color: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-django-app
      color: blue
  template:
    metadata:
      labels:
        app: simple-django-app
        color: blue
    spec:
      containers:
      - name: simple-django-app
        image: tapashranjannandi/simple-django-app-1:blue
        ports:
        - containerPort: 8000
        env: 
          - name: ALLOWED_HOSTS
            value: "*"

