apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-django-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: django.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-django-app-service
            port:
              number: 8000

