apiVersion: v1
kind: Service
metadata:
  name: simple-django-app-service
spec:
  selector:
    app: simple-django-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32004
  type: NodePort

